export const appRoutes = {
  HOME: "/",
  GAMES: "/games",
  BASIC: "/basic",
  INTERMEDIATE: "/intermediate",
  ADVANCED: "/advanced",
  VOCABULARY: "/vocabulary",
  GRAMMAR: "/grammar",
  VERBS: "/verbs",
  FINAL_TEST: "/final-test",
  RANKING: "/ranking",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PROFILE: "/profile",
  GUIDE: "/guide",
  INDEX_MENU: "/index-menu",
  CONTACT: "/contact",
  SITE_MAP: "/site-map",
  ABOUT: "/about",
};

export const appNames = {
  HOME: "Home",
  GAMES: "Juegos",
  BASIC: "Basic",
  INTERMEDIATE: "Intermediate",
  ADVANCED: "Advanced",
  VOCABULARY: "Vocabulary",
  GRAMMAR: "Grammar",
  VERBS: "Verbs",
  FINAL_TEST: "Final-test",
  RANKING: "Ranking",
  LOGIN: "Login",
  SIGNUP: "Signup",
  PROFILE: "Perfil",
  GUIDE: "Guía",
  INDEX_MENU: "Index menu",
  CONTACT: "Contacto",
  SITE_MAP: "Mapa del sitio",
  ABOUT: "About",
};
